#!/bin/sh
#
#

DEPLOY_REPO=castequality.github.com
DEPLOY_TO="../$DEPLOY_REPO"
if ! [ -d  $DEPLOY_TO ]; then
  printf "Missing deploy repo! Checking out from git..."
  git clone https://github.com/castequality/$DEPLOY_REPO $DEPLOY_TO
  printf "Checked out! Moving on..."
fi

alias deploy_dir='cd $DEPLOY_TO'
DIRECTORY=$(pwd)

# kill 'yeoman server' if running
pid=$(ps -ef | grep yeoman | grep -v grep | awk '{print $2}')
if ! [ -z "$pid" ]; then
  printf "killing 'yeoman server'..."
  kill $pid && printf "killed 'yeoman server'!" 
fi

yeoman install
yeoman build

deploy_dir
rm -rf *
cp -r $DIRECTORY/dist/* .
git add .
DATE=`date +%Y-%m-%d`
git commit -a -m "auto-deploy on $DATE"
git push origin master